### ISSUE TITLE
A few italicised terms aren’t given the appropriate xml:lang attribute

### ISSUE THREAD

**Issue by robinwhittleton** [tassos/okakura-kakuzo_the-book-of-tea#5]
For example, subsequent declarations of `roji` are wrapped with `<span xml:lang="ja">` (great!) but the first one is just `<i>roji</i>` instead of `<i xml:lang="ja">roji</i>`. Same for `machiai` - could you search and fix any more of these?

**Comment by tassos** [comment]
This was resolved in e779dc4
