### ISSUE TITLE
Some missing section breaks

### ISSUE THREAD

**Issue by robinwhittleton** [tassos/okakura-kakuzo_the-book-of-tea#6]
Unfortunately Gutenberg isn’t great at preserving section breaks in their source text, so I usually do a sweep for missing ones. Flicking through the scan PDF I came across this in chapter one:

![Example of a section break missing in chapter 1](https://user-images.githubusercontent.com/7414/50606664-d288b980-0ec6-11e9-8b0b-34b8db1b66c4.png)

To include this in our text, I’d insert a standard `<hr/>` before `<p>The earliest record of tea…`.

Can you add this, quickly scan through the rest of the PDF to see if there are any other missing section breaks and add any you find?

**Comment by tassos** [comment]
Surprisingly enough, this was the only section break in the whole book! Good catch @robinwhittleton . This is now fixed at e1b6207

**Comment by tassos** [comment]
Actually, was really fixed in a2ef374
