### ISSUE TITLE
Add some more lang italics where appropriate

### ISSUE THREAD

**Issue by robinwhittleton** [tassos/okakura-kakuzo_the-book-of-tea#7]
There are some Japanese terms in the original that aren’t proper nouns, but aren’t italicised. For our usage I’m happy to keep their initial capital I think, but I’d still like italicisation and an `xml:lang` for the first instance at least. For example: `Tokonoma` and `Kakoi`.

**Comment by tassos** [comment]
Thanks @robinwhittleton ! I did miss `Kakoi` indeed, but for `Tokonoma`, I followed the rule that says that if the word is in Merriam-Webster, we don't italicize it (https://standardebooks.org/contribute/typography#italics-language)

**Comment by robinwhittleton** [comment]
Oops, I’d missed that Tokonoma is in there 🤦‍♂️ Generally leave it unitalicised in that case.

**Comment by tassos** [comment]
This was addressed in 806fdc
